langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: otAL+3bp+YGLGra7gR4P2OlUZ87RiEYPC/BVdXvzaisfoO/R9Z45lzv8M/tlPsxEC9QR86+x8kwc5FuhWfQWXPi5XOI1UjlQMWQ64i+F4BhjVbP6qDI50Jj9yyEM9BA7LpLnJjo6xIPHmlOtBvVJ06jiyC0J3jntMx8lmAvNOvDviEqhH6XdkSr1bI0l9InQDVzZJy0i8kY8zaVzRhNKS/o4jyMzXh82KPvbDmn6kzU49/NuppC0gb9KTVA8JdXetn8Kurj/ME40EbqgjHIrPnwLCZuvt/ktAjtejjBC8iN+LrwNV7nFVu0iNGFYzyH7h0HEpxUm7mJVR9VkkiX5TlyPUlf6TGfXv4hpBLv7bnm8khLzwuZg6lFMXwsrWBn8sy7uMSfModqAbiKMJXxPF4mTUT8qbmo1VnbC+r7U7bV5intkVnOidbxVbgy1q5dRhF9txymolW69b+80WG35vRUkoj236/NQSNQpn6OK8Nme4P8DHi1O8k21hrijpAKw9EcHftE2I3FqLeoK6JCUEV41wiYFex5hBqdR4j0fU2F9DFkkf2rTwUo+YyKp/YNBYNh1zOZvbCg37pq/YpJBfFuI/zUjCzLgn936su/JQ3mQa/g/SukXwEKkeTzIQxM41V+Em2ojtcMjezVFucmHY5uc1nN0wkR8ckFplwhAcMc=
  app: shielded-falls-56694
  run: rails db:migrate
