langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: eV5QpIKBpBdJqTRqQyENzx/5i1ZGfHulBTz2dSDF8h5evb8RgMiQG+Uy9Rgp4ficFfMG4qXBCw8G/v+b2O9WoN18caypb/DlWV+Uhscj/F+lAJ7t2W2pVkSbVjwG/13vvq7nKH3KK5g1a8m2AOCV9kbT7ECh3O6ZLEkVCt+WSYUrJGuhob2VDqQsnQBmHkw28HumhgGPwsWQFhhg5Uj0cV5Y5TmayqyIveFM/XX5njSJ4GjNFjM1+1r7iUPKb5cTasNJ6ACokqz+KNnUiTUTubG2+xlKqeh/QFiiRvBxpQBDo/sQt7yHqK5vIFLJwoqDe0purOqsiXhLb/kP3VOGnzTaOIwtoCWANmXYmVmB45kMM7IkLwhorfHbrICMCMDJwypbaLPERVj+uJTKkj4vXrjnGzRX2+RDc5OOMDOT3moxm72liFdTi40tyymUOEd9JePZUqeSAj6lY0K1cSRlr00WJXAxxMjbaKntvQbzIOwdXV55iq222RuyHkcCRRotKV5tOcexn5Mn65yCzSchNpgIX5UN44pAmELYv92dMgslp9d+bZoqO8N16D4FMOfsr16fR1smeisn+E/VLsZReYVGb6r6KxuCwCaOzGBzJ7771BwpBdrHgHEIJayp8conIdR5BRfYAul8CCLwqtpZOamJxbWPof9v47oxDToYu+U=
  app: shielded-falls-56694
  run: rails db:migrate
